### ISSUE TITLE
New name, please!

### ISSUE THREAD

**Issue by mvassaux** [UCL-CCS/SCEMa#20]
What could we replace "DeaLAMMPS" by? 

It is a Finite Element and Molecular Dynamics coupling workflow based on the Heterogeneous or Hybrid multiscale method (depending on who you ask).

It is ideal, somehow, to predict material properties.

**Comment by velocirobbie** [comment]
Workflow for HybrId Multiscale SimulatIon, Yes!
WHIMSY

**Comment by velocirobbie** [comment]
CHUM | Coupling Hybrid mUltiscale Methods
WRHYME | WoRkflow for HYbrid Multiscale mEthods
WHIMS | Workflow for HybrId Multiscale Simulation

**Comment by velocirobbie** [comment]
MUESLI | MUltiscalE SimuLatIon
WHYS | Workflow for HYbrid Simulation
and finally, a genuine suggestions from acronymify.com
WORST | WORkflow SimulaTion

**Comment by mvassaux** [comment]
the BONUS (Bridging atOmic to coNtinuum concUrrent multiScale) workflow
the BOURNE (Bridging atOmic continUum concuRreNt multiscalE) ~~legacy~~ method

**Comment by velocirobbie** [comment]
these are terrible, only 5% of the letters are at the start of words!!

**Comment by mvassaux** [comment]
Done, WRHYME (WoRkflow for HYbrid Multiscale mEthods) won the vote (100%, one participant).

**Comment by velocirobbie** [comment]
Did you ask peter?

**Comment by mvassaux** [comment]
SCEMa that is!
